app <- ShinyDriver$new("../../")
app$snapshotInit("test")

app$snapshot(list(output = "formatted_des"))
app$setInputs(`des-dataset_iris_singleextract-filter1-col` = character(0))
app$snapshot(list(output = "formatted_des"))
app$setInputs(`des-dataset_iris_singleextract-filter1-col` = "Petal.Length")
app$setInputs(`des-dataset_iris_singleextract-filter1-vals` = "4.7")
app$setInputs(`des-dataset_iris_singleextract-select` = "Species")
app$snapshot(list(output = "formatted_des"))
